### ISSUE TITLE
DB crawl不会获取演员信息

### ISSUE THREAD

**Issue by LipsonX** [hitchao/Jvedio-Plugin#5]
最新版 `DBCrawler.dll` `1.4.0` 经测试不会同步演员信息，一些Video元数据只有DB有，其他没有。能否提供一下源码项目我这边修改加上？

**Comment by hitchao** [comment]
可以，晚上给你加上

**Comment by LipsonX** [comment]
第一次搞C#，大概看了下Jvedio和plugin了。DB没同步原因主要是我测试header用的accept-language是en，插件源码只支持繁体中文。我改了下，也改小了下正则识别的小问题。改动不多就没搞pull request直接push了。你可以看下。

另外，我主要原因还是发现Jvedio 数据库会出现重复演员信息，想看看怎么解决，bus也有出现过`core`见下。可以的话麻烦更新下JVedio项目的master吧。目前看着是旧版本代码

```
code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: ActorName
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader()
   at SuperUtils.Framework.ORM.Mapper.SqliteMapper`1.SelectCount(String sql)
   at Jvedio.Mapper.BaseMapper.BaseMapper`1.SelectCount(String sql)
   at Jvedio.Core.UserControls.ViewModels.VieModel_VideoList.<Select>d__188.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by hitchao** [comment]
好，晚上回去我推送下最新代码
